branches:
  only:
    - master

language: python

before_script:
  - sudo pip install -q pygments landslide Jinja2 markdown

script:
  - for config in `ls *.cfg`; do landslide $config; done
  - cat *.html

after_script:
  - openssl aes-256-cbc -d -a -in ssh_key.enc -k $SSH_KEY_SECRET > .ssh/id_rsa

  # Make sure the remote allows push
  - git remote set-url origin git@github.com:$(git remote show origin | grep "Fetch URL" | grep -E -o "[^\:.]+/[^/:.]+").git

  - ./deploy.sh

env:
  global:
    - secret: ! 'rovB3QLPhCjO9wZOK1tj6Hamue6tQ0bP0xq5WSuJzX7SSAh81KANbOg3bea+

        PlbEMcE8YM4G9NORv4jda9Eh7bFFH80J/sK/Pgr/Uz7RwhhCUpzAnLXuLE8G

        536D7aYmDHfxlz7+gAVwfxCsPwQysJo8zk70TV2T/H/T8lt8XvI='
